/** Centralized backend route paths, mirroring backend/src/routes/index.ts. */
export const ENDPOINTS = {
  health: "/health",
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    me: "/auth/me",
    refresh: "/auth/refresh",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verify: "/auth/verify",
  },
  users: {
    list: "/users",
    byId: (id: string) => `/users/${id}`,
    suspend: (id: string) => `/users/${id}/suspend`,
    reactivate: (id: string) => `/users/${id}/reactivate`,
    adminRole: (id: string) => `/users/${id}/admin-role`,
  },
  students: {
    byId: (id: string) => `/students/${id}`,
    dashboard: (id: string) => `/students/${id}/dashboard-summary`,
    onboarding: (id: string) => `/students/${id}/onboarding`,
  },
  parents: {
    byId: (id: string) => `/parents/${id}`,
    children: (id: string) => `/parents/${id}/children`,
    child: (id: string, childId: string) => `/parents/${id}/children/${childId}`,
    dashboard: (id: string) => `/parents/${id}/dashboard-summary`,
    onboarding: (id: string) => `/parents/${id}/onboarding`,
    settings: (id: string) => `/parents/${id}/settings`,
  },
  reports: {
    list: "/reports",
    byId: (bookingId: string) => `/reports/${bookingId}`,
    export: (bookingId: string) => `/reports/${bookingId}/export`,
  },
  payments: {
    summary: (parentId: string) => `/payments/${parentId}/summary`,
    list: (parentId: string) => `/payments/${parentId}`,
    byId: (parentId: string, paymentId: string) => `/payments/${parentId}/${paymentId}`,
    export: (parentId: string, paymentId: string) => `/payments/${parentId}/${paymentId}/export`,
    methods: (parentId: string) => `/payments/${parentId}/methods`,
    method: (parentId: string, methodId: string) => `/payments/${parentId}/methods/${methodId}`,
    setDefaultMethod: (parentId: string, methodId: string) => `/payments/${parentId}/methods/${methodId}/default`,
    adminList: "/payments/admin",
    adminById: (paymentId: string) => `/payments/admin/${paymentId}`,
    refund: (paymentId: string) => `/payments/admin/${paymentId}/refund`,
  },
  invoices: {
    mine: "/invoices/mine",
    byId: (invoiceId: string) => `/invoices/${invoiceId}`,
    download: (invoiceId: string) => `/invoices/${invoiceId}/download`,
    adminList: "/invoices/admin",
    adminById: (invoiceId: string) => `/invoices/admin/${invoiceId}`,
  },
  tutors: {
    search: "/tutors/search",
    saved: "/tutors/saved",
    byId: (id: string) => `/tutors/${id}`,
    settings: (id: string) => `/tutors/${id}/settings`,
    reviews: (id: string) => `/tutors/${id}/reviews`,
    availability: (id: string) => `/tutors/${id}/availability`,
    availabilityRules: (id: string) => `/tutors/${id}/availability-rules`,
    availabilityBlocks: (id: string) => `/tutors/${id}/availability-blocks`,
    availabilityBlock: (id: string, blockId: string) => `/tutors/${id}/availability-blocks/${blockId}`,
    dashboard: (id: string) => `/tutors/${id}/dashboard-summary`,
    performance: (id: string) => `/tutors/${id}/performance`,
    save: (id: string) => `/tutors/${id}/save`,
    students: (id: string) => `/tutors/${id}/students`,
    student: (id: string, studentId: string) => `/tutors/${id}/students/${studentId}`,
    studentNotes: (id: string, studentId: string) => `/tutors/${id}/students/${studentId}/notes`,
  },
  tutorVerification: {
    status: (tutorId: string) => `/tutor-verification/${tutorId}/status`,
    apply: "/tutor-verification/apply",
    queue: "/tutor-verification/admin/queue",
    application: (applicationId: string) => `/tutor-verification/admin/queue/${applicationId}`,
    approve: (applicationId: string) => `/tutor-verification/admin/queue/${applicationId}/approve`,
    reject: (applicationId: string) => `/tutor-verification/admin/queue/${applicationId}/reject`,
    requestInfo: (applicationId: string) => `/tutor-verification/admin/queue/${applicationId}/request-info`,
  },
  smartMatch: {
    recommend: "/smart-match",
  },
  bookings: {
    list: "/bookings",
    create: "/bookings",
    byId: (id: string) => `/bookings/${id}`,
    reschedule: (id: string) => `/bookings/${id}/reschedule`,
    cancel: (id: string) => `/bookings/${id}/cancel`,
    checkout: (id: string) => `/bookings/${id}/checkout`,
  },
  lessons: {
    byBooking: (bookingId: string) => `/lessons/${bookingId}`,
    participants: (bookingId: string) => `/lessons/${bookingId}/participants`,
    start: (bookingId: string) => `/lessons/${bookingId}/start`,
    end: (bookingId: string) => `/lessons/${bookingId}/end`,
    summary: (bookingId: string) => `/lessons/${bookingId}/summary`,
    notes: (bookingId: string) => `/lessons/${bookingId}/notes`,
    messages: (bookingId: string) => `/lessons/${bookingId}/messages`,
    resources: (bookingId: string) => `/lessons/${bookingId}/resources`,
    whiteboard: (bookingId: string) => `/lessons/${bookingId}/whiteboard`,
  },
  reviews: {
    submit: "/reviews",
    adminList: "/reviews/admin",
    moderate: (id: string) => `/reviews/${id}/moderate`,
  },
  earnings: {
    summary: (tutorId: string) => `/earnings/${tutorId}/summary`,
    list: (tutorId: string) => `/earnings/${tutorId}`,
    export: (tutorId: string) => `/earnings/${tutorId}/export`,
    payouts: (tutorId: string) => `/earnings/${tutorId}/payouts`,
    adminPayouts: "/earnings/admin/payouts",
    adminEntries: "/earnings/admin/entries",
  },
  resources: {
    list: (tutorId: string) => `/resources/${tutorId}`,
    byId: (tutorId: string, resourceId: string) => `/resources/${tutorId}/${resourceId}`,
    share: (tutorId: string, resourceId: string) => `/resources/${tutorId}/${resourceId}/share`,
    unshare: (tutorId: string, resourceId: string, studentId: string) => `/resources/${tutorId}/${resourceId}/share/${studentId}`,
  },
  admin: {
    overview: "/admin/overview",
    analytics: "/admin/analytics",
    search: "/admin/search",
    students: "/admin/students",
    parents: "/admin/parents",
    tutors: "/admin/tutors",
    bookings: "/admin/bookings",
    lessons: "/admin/lessons",
    financeReconciliation: "/admin/finance/reconciliation",
    auditLogs: "/admin/audit-logs",
    settings: "/admin/settings",
    announcements: "/admin/announcements",
  },
  complaints: {
    list: "/complaints",
    create: "/complaints",
    byId: (id: string) => `/complaints/${id}`,
    assign: (id: string) => `/complaints/${id}/assign`,
    resolve: (id: string) => `/complaints/${id}/resolve`,
  },
  support: {
    create: "/support",
    mine: "/support/mine",
    list: "/support",
    byId: (id: string) => `/support/${id}`,
    messages: (id: string) => `/support/${id}/messages`,
    update: (id: string) => `/support/${id}`,
  },
  content: {
    listPublished: "/content",
    bySlug: (slug: string) => `/content/slug/${slug}`,
    adminList: "/content/admin",
    adminById: (id: string) => `/content/admin/${id}`,
    adminVersions: (id: string) => `/content/admin/${id}/versions`,
    create: "/content/admin",
    update: (id: string) => `/content/admin/${id}`,
    setStatus: (id: string) => `/content/admin/${id}/status`,
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: "/notifications/read-all",
  },
  search: {
    query: "/search",
  },
  recommendations: {
    forMe: "/recommendations/me",
    summary: "/recommendations/summary",
  },
  featureFlags: {
    get: "/feature-flags",
    update: "/feature-flags",
  },
  analyticsEvents: {
    record: "/analytics/events",
    counts: "/analytics/events/counts",
  },
  mastery: {
    forStudent: (studentId: string) => `/mastery/${studentId}`,
    history: (studentId: string, topicId: string) => `/mastery/${studentId}/history/${topicId}`,
  },
  goals: {
    mine: "/goals/mine",
    forStudent: (studentId: string) => `/goals/student/${studentId}`,
    create: "/goals",
    updateProgress: (id: string) => `/goals/${id}/progress`,
    remove: (id: string) => `/goals/${id}`,
  },
  achievements: {
    forStudent: (studentId: string) => `/achievements/${studentId}`,
  },
  learning: {
    profile: "/learning/profile",
    progress: "/learning/progress",
    subject: (subjectId: string) => `/learning/subjects/${subjectId}`,
    topic: (topicId: string) => `/learning/topics/${topicId}`,
    revision: "/learning/revision",
    insights: "/learning/insights",
    studyPlan: "/learning/study-plan",
  },
  topics: {
    list: (subjectId?: string) => (subjectId ? `/topics?subjectId=${subjectId}` : "/topics"),
  },
  practiceQuestions: {
    byTopic: (topicId: string) => `/questions?topicId=${topicId}`,
  },
  homework: {
    list: "/homework/mine",
    listForStudent: (studentId: string) => `/homework/student/${studentId}`,
    listForTutor: "/homework/tutor",
    listForLesson: (bookingId: string) => `/homework/lesson/${bookingId}`,
    getById: (id: string) => `/homework/${id}`,
    create: "/homework",
    saveAnswers: (id: string) => `/homework/${id}/answers`,
    submit: (id: string) => `/homework/${id}/submit`,
    review: (id: string) => `/homework/${id}/review`,
  },
} as const;
